# Site settings
title: Robert Gunner Feie
email: robert.gunner.feie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website and blog for Robert Gunner Feie
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rfeie.com" # the base hostname & protocol for your site

name: Robert Gunner Feie
# Build settings
markdown: kramdown

sass:
  style: compressed
  sass_dir: _sass

gems:
  - jekyll-sitemap

kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge


